name: Bump uv lockfile

permissions:
  contents: write
  pull-requests: write

on:
  workflow_dispatch:
  schedule:
    # run every Monday at noon UTC (6 AM CST/Saskatchewan)
    - cron: 0 12 * * MON

jobs:
  bump-dependencies:
    uses: "daq/gha_workflows/.github/workflows/bump_uv.yml@main"
    secrets: inherit
